-- MySQL Script generated by MySQL Workbench
-- Sun Oct 29 17:57:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proyecto_clase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto_clase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto_clase` DEFAULT CHARACTER SET utf8 ;
USE `proyecto_clase` ;

-- -----------------------------------------------------
-- Table `proyecto_clase`.`tipousu_tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_clase`.`tipousu_tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `proyecto_clase`.`tipousu_tipo_usuario` (
  `tipousu_pk` INT NOT NULL AUTO_INCREMENT,
  `tipousu_nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`tipousu_pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clase`.`usu_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_clase`.`usu_usuarios` ;

CREATE TABLE IF NOT EXISTS `proyecto_clase`.`usu_usuarios` (
  `usu_pk` INT NOT NULL AUTO_INCREMENT,
  `tipousu_tipo_usuario_tipousu_pk` INT NOT NULL,
  `usu_nombre` VARCHAR(255) NOT NULL,
  `usu_username` VARCHAR(45) NOT NULL,
  `usu_password` VARCHAR(255) NOT NULL,
  `usu_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usu_pk`, `tipousu_tipo_usuario_tipousu_pk`),
  INDEX `fk_usu_usuarios_tipousu_tipo_usuario1_idx` (`tipousu_tipo_usuario_tipousu_pk` ASC),
  CONSTRAINT `fk_usu_usuarios_tipousu_tipo_usuario1`
    FOREIGN KEY (`tipousu_tipo_usuario_tipousu_pk`)
    REFERENCES `proyecto_clase`.`tipousu_tipo_usuario` (`tipousu_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clase`.`con_contenido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_clase`.`con_contenido` ;

CREATE TABLE IF NOT EXISTS `proyecto_clase`.`con_contenido` (
  `con_pk` INT NOT NULL AUTO_INCREMENT,
  `con_titulo` VARCHAR(60) NOT NULL,
  `con_codigo` VARCHAR(255) NOT NULL,
  `con_imagen` VARCHAR(255) NULL,
  `con_fecha_creacion` DATETIME NOT NULL,
  `con_stock` INT NOT NULL,
  PRIMARY KEY (`con_pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clase`.`pro_productora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_clase`.`pro_productora` ;

CREATE TABLE IF NOT EXISTS `proyecto_clase`.`pro_productora` (
  `pro_pk` INT NOT NULL AUTO_INCREMENT,
  `pro_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pro_pk`),
  UNIQUE INDEX `pro_nombre_UNIQUE` (`pro_nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clase`.`dir_directores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_clase`.`dir_directores` ;

CREATE TABLE IF NOT EXISTS `proyecto_clase`.`dir_directores` (
  `dir_pk` INT NOT NULL AUTO_INCREMENT,
  `dir_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dir_pk`),
  UNIQUE INDEX `dir_nombre_UNIQUE` (`dir_nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clase`.`pel_pelicula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_clase`.`pel_pelicula` ;

CREATE TABLE IF NOT EXISTS `proyecto_clase`.`pel_pelicula` (
  `pel_pk` INT NOT NULL AUTO_INCREMENT,
  `con_contenido_con_pk` INT NOT NULL,
  `pro_productora_pro_pk` INT NOT NULL,
  `dir_directores_dir_pk` INT NOT NULL,
  PRIMARY KEY (`pel_pk`, `con_contenido_con_pk`, `pro_productora_pro_pk`, `dir_directores_dir_pk`),
  INDEX `fk_dvd_DVD_pro_productora1_idx` (`pro_productora_pro_pk` ASC),
  INDEX `fk_dvd_DVD_dir_directores1_idx` (`dir_directores_dir_pk` ASC),
  CONSTRAINT `fk_dvd_DVD_con_contenido1`
    FOREIGN KEY (`con_contenido_con_pk`)
    REFERENCES `proyecto_clase`.`con_contenido` (`con_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dvd_DVD_pro_productora1`
    FOREIGN KEY (`pro_productora_pro_pk`)
    REFERENCES `proyecto_clase`.`pro_productora` (`pro_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dvd_DVD_dir_directores1`
    FOREIGN KEY (`dir_directores_dir_pk`)
    REFERENCES `proyecto_clase`.`dir_directores` (`dir_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clase`.`disc_discografica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_clase`.`disc_discografica` ;

CREATE TABLE IF NOT EXISTS `proyecto_clase`.`disc_discografica` (
  `disc_pk` INT NOT NULL AUTO_INCREMENT,
  `disc_nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`disc_pk`),
  UNIQUE INDEX `disc_nombre_UNIQUE` (`disc_nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clase`.`mus_musica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_clase`.`mus_musica` ;

CREATE TABLE IF NOT EXISTS `proyecto_clase`.`mus_musica` (
  `mus_pk` INT NOT NULL AUTO_INCREMENT,
  `con_contenido_con_pk` INT NOT NULL,
  `disc_discografica_disc_pk` INT NULL,
  PRIMARY KEY (`mus_pk`, `con_contenido_con_pk`),
  INDEX `fk_mus_musica_disc_discografica1_idx` (`disc_discografica_disc_pk` ASC),
  CONSTRAINT `fk_cd_CD_con_contenido1`
    FOREIGN KEY (`con_contenido_con_pk`)
    REFERENCES `proyecto_clase`.`con_contenido` (`con_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mus_musica_disc_discografica1`
    FOREIGN KEY (`disc_discografica_disc_pk`)
    REFERENCES `proyecto_clase`.`disc_discografica` (`disc_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clase`.`pres_prestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_clase`.`pres_prestamo` ;

CREATE TABLE IF NOT EXISTS `proyecto_clase`.`pres_prestamo` (
  `con_contenido_con_pk` INT NOT NULL,
  `usu_usuarios_usu_pk` INT NOT NULL,
  `pres_fecha_prestamo` DATETIME NOT NULL,
  PRIMARY KEY (`con_contenido_con_pk`, `usu_usuarios_usu_pk`),
  INDEX `fk_pres_prestamo_usu_usuarios1_idx` (`usu_usuarios_usu_pk` ASC),
  CONSTRAINT `fk_pres_prestamo_con_contenido`
    FOREIGN KEY (`con_contenido_con_pk`)
    REFERENCES `proyecto_clase`.`con_contenido` (`con_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pres_prestamo_usu_usuarios1`
    FOREIGN KEY (`usu_usuarios_usu_pk`)
    REFERENCES `proyecto_clase`.`usu_usuarios` (`usu_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clase`.`lib_libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_clase`.`lib_libro` ;

CREATE TABLE IF NOT EXISTS `proyecto_clase`.`lib_libro` (
  `lib_pk` INT NOT NULL AUTO_INCREMENT,
  `con_contenido_con_pk` INT NOT NULL,
  `lib_numero_paginas` INT NOT NULL,
  `lib_capitulo_muestra` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`lib_pk`, `con_contenido_con_pk`),
  CONSTRAINT `fk_lib_libro_con_contenido1`
    FOREIGN KEY (`con_contenido_con_pk`)
    REFERENCES `proyecto_clase`.`con_contenido` (`con_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clase`.`canc_canciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_clase`.`canc_canciones` ;

CREATE TABLE IF NOT EXISTS `proyecto_clase`.`canc_canciones` (
  `canc_pk` INT NOT NULL AUTO_INCREMENT,
  `canc_nombre` VARCHAR(255) NOT NULL,
  `canc_orden` INT NOT NULL,
  `mus_musica_mus_pk` INT NOT NULL,
  PRIMARY KEY (`canc_pk`, `mus_musica_mus_pk`),
  INDEX `fk_canc_canciones_cd_CD1_idx` (`mus_musica_mus_pk` ASC),
  CONSTRAINT `fk_canc_canciones_mus_musica1`
    FOREIGN KEY (`mus_musica_mus_pk`)
    REFERENCES `proyecto_clase`.`mus_musica` (`mus_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clase`.`act_actores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_clase`.`act_actores` ;

CREATE TABLE IF NOT EXISTS `proyecto_clase`.`act_actores` (
  `act_pk` INT NOT NULL AUTO_INCREMENT,
  `act_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`act_pk`),
  UNIQUE INDEX `act_nombre_UNIQUE` (`act_nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clase`.`pelact_pelicula_actores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_clase`.`pelact_pelicula_actores` ;

CREATE TABLE IF NOT EXISTS `proyecto_clase`.`pelact_pelicula_actores` (
  `pel_pelicula_pel_pk` INT NOT NULL,
  `act_actores_act_pk` INT NOT NULL,
  PRIMARY KEY (`pel_pelicula_pel_pk`, `act_actores_act_pk`),
  INDEX `fk_dvd_DVD_has_act_actores_act_actores1_idx` (`act_actores_act_pk` ASC),
  CONSTRAINT `fk_dvd_DVD_has_act_actores_pel_pelicula1`
    FOREIGN KEY (`pel_pelicula_pel_pk`)
    REFERENCES `proyecto_clase`.`pel_pelicula` (`pel_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dvd_DVD_has_act_actores_act_actores1`
    FOREIGN KEY (`act_actores_act_pk`)
    REFERENCES `proyecto_clase`.`act_actores` (`act_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
